import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pablo Carrera Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Pablo Carrera Blog</a>
        </h1>

        <p className={styles.description}>
          Get soon started soon{' '}
          <code className={styles.code}>soon</code>
        </p>

        <div className={styles.grid}>
          <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about soon.</p>
          </a>

          <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn soon!</p>
          </a>

          <a
            href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy soon.</p>
          </a>

          <a
            href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your soon.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/assets/img/pablines.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
